# Generated by Django 4.0.3 on 2022-04-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umdsite', '0003_user_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donated_medicine',
            name='user_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requested_medicine',
            name='user_name',
            field=models.CharField(max_length=10),
        ),
    ]
