# Generated by Django 4.0.3 on 2022-04-10 01:57

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umdsite', '0005_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='ul_name',
            field=models.OneToOneField(on_delete=builtins.callable, to='umdsite.user_registration'),
        ),
    ]
