# Generated by Django 4.0.3 on 2022-04-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umdsite', '0006_alter_user_login_ul_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='ul_name',
            field=models.CharField(max_length=10),
        ),
    ]
