# Generated by Django 4.0.3 on 2022-04-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umdsite', '0002_rename_donate_medicine_donated_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=50)),
            ],
        ),
    ]
