# Generated by Django 4.0.3 on 2022-04-10 01:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umdsite', '0004_alter_donated_medicine_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ul_pass', models.CharField(max_length=10)),
                ('ul_name', models.ForeignKey(on_delete=builtins.callable, to='umdsite.user_registration')),
            ],
        ),
    ]
